services:
  ana-assistent:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - vendor-data:/var/www/html/vendor
    working_dir: /var/www/html

volumes:
  vendor-data:
